### ISSUE TITLE
IPS 4.3 Not working

### ISSUE THREAD

**Issue by Jord38** [Lavoaster/IPS-SteamLoginMethod#100]
On login with steam I get this error:
https://i.gyazo.com/218c276964dd0f51550d26d6c10ce098.png

**Comment by Lavoaster** [comment]
This sounds related to #98.

**Comment by Lavoaster** [comment]
Can you try this? https://github.com/Lavoaster/IP.Board-Steam-Authentication-Method/archive/2.0.4.zip

**Comment by Jord38** [comment]
Uploading a new version didn't fix it so instead I tried reinstalling the plugin, now it's not showing up under login handlers.

**Comment by Striven90** [comment]
Issue related to Valve's recent SSL/TLS switch mentioned here: https://www.reddit.com/r/Steam/comments/8a7gsu/steam_openid_broken_for_many_websites_fix_inside/

Edit file system/Login/Steam.php Line 278

from:
`preg_match("#^http://steamcommunity.com/openid/id/([0-9]{17,25})#", urldecode($_GET['openid_claimed_id']), $matches);`

to:
`preg_match("#^https://steamcommunity.com/openid/id/([0-9]{17,25})#", urldecode($_GET['openid_claimed_id']), $matches);`

**Comment by madman32395** [comment]
@Striven90 this should have been implemented in #98

**Comment by RustSociety** [comment]
Confirmed, not working on 4.3. You can sign in or register, but the option to sync avatars and link steam to existing accounts no longer exist.

**Comment by Pydrex** [comment]
Hello,

We're having a fairly urgent issue with this (PAID) version. Updated the Uploads and the XML however still getting the problem where users can't sync there profiles.

We need this as we use it for our app to check someones account before play.

**Comment by Pydrex** [comment]
Upon further review.

Registering for a forum account using steam works fine, you can go through the whole process fine.
Login with steam works fine using that registered account

/settings/steam
De-Associating the account and re-adding just returns you back to the Sign In with Steam even after login, this does this everytime so this part still seems broken

**Comment by giovaniferrarotrivelli** [comment]
Confirmed. Still doesn't work.

**Comment by madman32395** [comment]
Pydrex, what are you paying for? Steam login is free.

**Comment by Lavoaster** [comment]
Please download [this](https://github.com/Lavoaster/IPS-SteamLoginMethod/releases/download/v3.0.0/steamlogin-3.0.0.zip) and follow the instructions in the readme for upgrading.
