### ISSUE TITLE
IPS 4.3 Login error

### ISSUE THREAD

**Issue by GeneralMitch** [Lavoaster/IPS-SteamLoginMethod#103]
This prob was posted before, but just in case my error is different, when trying to login  Im getting this error  (from my system logs)

`Error: Access to undeclared static property: IPS\Login\Handler\Standard::$icon (0)
#0 /var/www/html/x279447/system/Theme/SandboxedTemplate.php(56): IPS\Theme\class_core_front_system->settings('overview', '\n<div class='ip...', true, true, -1, false, Array, false, false)
#1 /var/www/html/x279447/applications/core/modules/front/system/settings.php(126): IPS\Theme\_SandboxedTemplate->__call('settings', Array)
#2 /var/www/html/x279447/applications/core/modules/front/system/settings.php(76): IPS\core\modules\front\system\_settings->_wrapOutputInTemplate('overview', '\n<div class='ip...')
#3 /var/www/html/x279447/system/Dispatcher/Controller.php(96): IPS\core\modules\front\system\_settings->manage()
#4 /var/www/html/x279447/applications/core/modules/front/system/settings.php(40): IPS\Dispatcher\_Controller->execute()
#5 /var/www/html/x279447/system/Dispatcher/Dispatcher.php(146): IPS\core\modules\front\system\_settings->execute()
#6 /var/www/html/x279447/index.php(13): IPS\_Dispatcher->run()
#7 {main}`

**Comment by Lavoaster** [comment]
Please download [this](https://github.com/Lavoaster/IPS-SteamLoginMethod/releases/download/v3.0.0/steamlogin-3.0.0.zip) and follow the instructions in the readme for upgrading.
