### ISSUE TITLE
1S111/1 Error

### ISSUE THREAD

**Issue by Hawk-HQ** [Lavoaster/IPS-SteamLoginMethod#106]
When trying to install for first time on IPS 4.3.1 I receive this error each time.

> 1S111/1 Table 'hqwebsite_forums.core_login_handlers' doesn't exist

Along with this....

> SELECT login_key FROM `core_login_handlers` WHERE login_key='steam'
Table 'hqwebsite_forums.core_login_handlers' doesn't exist

**Comment by Hawk-HQ** [comment]
Any ETA?

**Comment by Lavoaster** [comment]
Please download [this](https://github.com/Lavoaster/IPS-SteamLoginMethod/releases/download/v3.0.0/steamlogin-3.0.0.zip) and follow the instructions in the readme for upgrading.
