### ISSUE TITLE
Login Handlers

### ISSUE THREAD

**Issue by namopsx** [Lavoaster/IPS-SteamLoginMethod#107]
im upload the contents of the upload folder to my forum root directory

install plugin in ACP

its no show in Login Handlers

**Comment by kuplion** [comment]
Having the same issue here, 2.0.4 freshly installed but not showing up in login handlers.

**Comment by mkassjanski** [comment]
Same here

**Comment by Osaxi** [comment]
I'm also having the same issue.

**Comment by Lebofly** [comment]
I'm still having this issue

**Comment by namopsx** [comment]
Me 2, Steam Login it does not show up in ACP Login Handlers,

**Comment by Lavoaster** [comment]
IPB 4.3 update is in the works.

**Comment by Lavoaster** [comment]
Please download [this](https://github.com/Lavoaster/IPS-SteamLoginMethod/releases/download/v3.0.0/steamlogin-3.0.0.zip) and follow the instructions in the readme for upgrading.
