### ISSUE TITLE
IP Board 4.3.3 Update | Invalid Steam ID being provided

### ISSUE THREAD

**Issue by TheGamingChief** [Lavoaster/IPS-SteamLoginMethod#113]
So after a fresh install of IP Board 4.3.3 and installing the application (following the provided directions) it seems as every-time someone tries to login with Steam it spits out "2147483647" as the player ID for some odd reason.

I've haven't found any error logs, however I'm still searching. Just wanted to check if this is a known issue with this new release.

**Comment by Lavoaster** [comment]
Is this using the version I posted on GitHub today?

**Comment by Lavoaster** [comment]
I only released it ~3 hours ago. Are you sure it's this one? https://github.com/Lavoaster/IPS-SteamLoginMethod/releases/tag/v3.0.0

**Comment by TheGamingChief** [comment]
Sorry about the late reply I had to look into that. I downloaded the version from the main from page of this repo (https://prnt.sc/jra6ck). I didn't realize that was not the newest version. I went ahead and completely removed that version, and installed the version you linked and I'm still having the same issue.

I've left all the login with Steam settings default (other than the API key ofc) and every time someone times to log in it still sets their Steam ID to "2147483647" (https://prnt.sc/jrag6s). I've gone into the DB itself and verified that the "steamid" column is being set as "2147483647" (https://prnt.sc/jrahon).

**Comment by Lavoaster** [comment]
Are you running on a 32bit or 64bit server?

**Comment by TheGamingChief** [comment]
We are running on Windows Server 2012 R2 with IIS, I know you said IIS can cause some issues, however do you think that could be causing the issue.

**Comment by Lavoaster** [comment]
To be honest, I don't think IIS is an issue anymore, but it will be an issue if your system is 32bit the Steam ID such as mine `76561198010571702` caused an integer overflow and PHP decided to use the maximum 32bit signed integer value, which is `2147483647`.

I'm going to push something up very soon that removes that type conversion, because it really don't need to be there.

**Comment by Lavoaster** [comment]
Alright, can you try downloading https://github.com/Lavoaster/IPS-SteamLoginMethod/releases/tag/v3.0.0 again?

**Comment by TheGamingChief** [comment]
Yeah that last update fixed the issue. Thanks for the help! Cheers m8

**Comment by Lavoaster** [comment]
Awesome. By chance, were you a new install or an upgrade from the 4.2 plugin?

**Comment by TheGamingChief** [comment]
New install.
