### ISSUE TITLE
Proper Redirect upon login

### ISSUE THREAD

**Issue by madman32395** [Lavoaster/IPS-SteamLoginMethod#51]
Main issue was fixed for 4.1.9 by Lindy ; Native login Handlers now work as intended, but steam still has issue.

Issue: Visit a page that requires login/permissions, login, and get redirected back to homepage instead of intended page.

https://invisionpower.com/4bugtrack/archived-reports/40131-ipsconnect-login-in-doesnt-redirect-to-the-current-page-r8199/

**Comment by madman32395** [comment]
This issue was reported fixed/verified by Brandon at IPS. IPS Ticket #986751

**Comment by K3RRR** [comment]
This issue still persists where users aren't redirected to the page they were on when signing in.

**Comment by Lavoaster** [comment]
This would have been fixed in the 4.3 update.
