### ISSUE TITLE
Sign out not clearing session

### ISSUE THREAD

**Issue by Lebofly** [Lavoaster/IPS-SteamLoginMethod#69]
I'm having a couple of issues with sign in/out, when users sign in sometimes it just redirects them to the sign in page again to go through an endless loop unless they go to the forum root and try again. Another issue is sign out takes you to the signed out page but upon returning to index you're still signed in. If someone wants to take a closer look at this let me know, I should also mention my forum is using ONLY steam as  login authentication (Normal Sign In/Out was disabled/hidden completely)

**Comment by island55** [comment]
i had the same issue, check here for my fix
https://github.com/Lavoaster/IP.Board-Steam-Authentication-Method/issues/68

**Comment by Lebofly** [comment]
Unfortunately I'm already running from the Github version, (Latest)

**Comment by madman32395** [comment]
Apache or Ngnix?

**Comment by Lebofly** [comment]
Apache

**Comment by madman32395** [comment]
Are you using a modified htaccess? Or the stock one from the friendly URL
area from the ACP?

**Comment by Lebofly** [comment]
Stock one
