### ISSUE TITLE
Says no API Key even though there is.

### ISSUE THREAD

**Issue by Bananastreet** [Lavoaster/IPS-SteamLoginMethod#83]
I keep getting an error stating that there is no API key.

`Exception: steam_err_noapi (0)
#0 C:\xampp\htdocs\forums\applications\steam\extensions\core\MemberSync\Steam.php(131): IPS\steam\_Update->__construct()
#1 [internal function]: IPS\steam\extensions\core\MemberSync\_Steam->onProfileUpdate(Object(IPS\Member), Array)
#2 C:\xampp\htdocs\forums\system\Member\Member.php(3004): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\forums\system\Member\Member.php(349): IPS\_Member->memberSync('onProfileUpdate', Array)
#4 C:\xampp\htdocs\forums\system\Login\Steam.php(142): IPS\_Member->save()
#5 C:\xampp\htdocs\forums\applications\core\modules\front\system\settings.php(559): IPS\Login\_Steam->authenticate(Object(IPS\Http\Url), Object(IPS\Member))
#6 [internal function]: IPS\core\modules\front\system\_settings->_profilesync()
#7 C:\xampp\htdocs\forums\applications\core\modules\front\system\settings.php(55): call_user_func(Array)
#8 C:\xampp\htdocs\forums\system\Dispatcher\Controller.php(94): IPS\core\modules\front\system\_settings->manage()
#9 C:\xampp\htdocs\forums\applications\core\modules\front\system\settings.php(35): IPS\Dispatcher\_Controller->execute()
#10 C:\xampp\htdocs\forums\system\Dispatcher\Dispatcher.php(129): IPS\core\modules\front\system\_settings->execute()
#11 C:\xampp\htdocs\forums\index.php(13): IPS\_Dispatcher->run()
#12 {main}`

But yet it still signs me in from steam and everything else.

![Image](https://puu.sh/uYpLR/64d1187662.png)

**Comment by madman32395** [comment]
Double checking is this for the Steam Display app or is this for the Steam Login Plugin?

**Comment by Terminuscentral** [comment]
Im getting the same error, the error comes after going to the steam page to log into steam. It comes back to the error. Im using a pc

**Comment by madman32395** [comment]
double check redirect scripts, double check file permissions and ownership permissions.

**Comment by Terminuscentral** [comment]
steam login plugin only currently
