### ISSUE TITLE
Show steam UID on profile

### ISSUE THREAD

**Issue by ChrisStark** [Lavoaster/IPS-SteamLoginMethod#88]
Is there an easy way to show the steam UID on the persons profile?

We make it mandatory that everyone logs in using your plugin however the reason is because we want it to automatically show UID on their profile?

**Comment by ChrisStark** [comment]
I have done this if anyone needs it.

**Comment by K3RRR** [comment]
@ChrisStark I could use this. If you could please contact me on steam at: http://steamcommunity.com/id/kerr/

**Comment by ChrisStark** [comment]
Here is the release on how to put it on your profile! hope this helps everyone

https://pastebin.com/0QJNm3Tz

**Comment by good-live** [comment]
@ChrisStark how did you made it mandatory to register with steam?

**Comment by ChrisStark** [comment]
we dont approve applications unless they are. but you can make it the only
option and therefor will force them to do so.

**Comment by ChrisStark** [comment]
Code was messed up I have updated so it will be correct now!
