### ISSUE TITLE
Receiving a template error

### ISSUE THREAD

**Issue by Gryphon109** [Lavoaster/IPS-SteamLoginMethod#89]
Hi, ever since I installed this I've been receiving a template error I followed the recommended IBP steps too no avail any help is extremely appreciated!
Error: [[Template core/front/global/loginPopup is throwing an error. This theme may be out of date. Run the support tool in the AdminCP to restore the default theme.]]

**Comment by madman32395** [comment]
Does this do this on the default (unmodified theme) ; if you no longer have a unmodified theme, goto the support tool and run it until it makes a fresh one for you.

I am assuming you're running 4.1.x or 4.2.x?

Are you CiC or Self Hosted?

**Comment by ThatBossGuy** [comment]
I'm running it on 4.1 yes, and it does do it on the unmodified theme, I also followed the support system and refresh the unmodified theme and I still got the error.
