### ISSUE TITLE
[REQUEST] Profile Completion

### ISSUE THREAD

**Issue by shadowtor** [Lavoaster/IPS-SteamLoginMethod#90]
IPB now has a profile completion section, would be awesome to see steam added to this
![firefox_2017-09-13_00-04-56](https://user-images.githubusercontent.com/4159051/30330032-493299d4-9817-11e7-926a-8012c46fb0f5.png)

**Comment by Lavoaster** [comment]
Part of this is actually done by the IPS 4.3 update. Albeit it won't add a visible field for the users steam page.

![](http://share.adamlav.in/s48b/Screen%20Shot%202018-06-05%20at%2021.33.24.png)
![](http://share.adamlav.in/s5Kz/Screen%20Shot%202018-06-05%20at%2021.34.50.png)
