### ISSUE TITLE
403 Forbidden Error on Steam Login

### ISSUE THREAD

**Issue by IlPicasso** [Lavoaster/IPS-SteamLoginMethod#97]
Suddenly I have been getting this errror on login

![image](https://user-images.githubusercontent.com/5110242/35878844-896d74d0-0b47-11e8-9355-93a941c32620.png)

**Comment by madman32395** [comment]
Permission or file ownership error most likely

**Comment by milanfon** [comment]
I'm having the same issue. I also thought it would be file permission error, but I've checked that and it's not the issue. Also tried to change the API key or reinstalling the plugin. Neither of these attemps worked.

**Comment by IlPicasso** [comment]
Checked the access log, the error log and system logs and I dont find anything

**Comment by madman32395** [comment]
if the files are good but still 403, hit me up on discord: MADMAN32395#1736 ; we can discuss FTP and ACP access, and I could take a peek when I get some time.

**Comment by WeirdPhrog** [comment]
Same error, please help
